### ISSUE TITLE
Module descriptors under META-INF not found

### ISSUE THREAD

**Issue by jafarre-bi** [apache/maven-compiler-plugin#966]
### Affected version

4.0.0-beta-2

### Bug description

jackson-core 3.0.0-RC9 has the module-info.class located at META-INF/versions/17/module-info.class.
This is correctly recognised when compiling with the plugin version 3.14.0, but it isn't recognised with plugin version 4.0.0-beta-2, and the build crashes because tools.jackson.core module can't be found by other modules that depend on it.
Is this a bug in the 4.x versions or an intentional change?

**Comment by desruisseaux** [comment]
Can you post the `<dependency>` block in the `pom.xml` file that declare this dependency? I would like to see in particular if a `<type>` is declared.

**Comment by jafarre-bi** [comment]
It's a transitive dependency of:
```
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
```
The dependency management is:
```
            <dependency>
                <groupId>tools.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>3.0.0-rc9</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```
Inside the BOM I see:
```
      <dependency>
        <groupId>tools.jackson.core</groupId>
        <artifactId>jackson-core</artifactId>
        <version>3.0.0-rc9</version>
      </dependency>
```

**Comment by desruisseaux** [comment]
Can you try to add the following line in the Jackson dependency?

```xml
      <type>modular-jar</type>
```

If the `module-info.class` file was ignored, it suggests that the Jackson JAR file was placed on the class-path rather than the module-path. When the type is not specified, or when the type is `jar`, Maven uses heuristic rules for deciding where to place the JAR file. There is maybe a regression in the heuristic rules of compiler plugin 4.0.0-beta-2. But when `classpath-jar` or `modular-jar` type is specified, there is no heuristic rules: the plugin will obey strictly to what have been specified. I would recommend to always specify these dependency types in a Maven 4 project for making the build more deterministic.

Nevertheless, there is maybe a regression in 4.0.0-beta-2 if we forgot to check in the `META-INF/services/` directory. I will investigate. In the meantime, if you have a chance to confirm whether `<type>modular-jar</type>` works, that would be nice to know since avoiding this kind of issue was the whole point of allowing explicit control on class-path versus module-path in Maven 4.

**Comment by jafarre-bi** [comment]
Ok, the results require some detailed explanation. As jackson-core is a transitive dependency of jackson-databind, I tried several things:
1. Making jackson-databind dependency modular-jar type -> No effect.
2. Making jackson-core dependency modular-jar type -> Compiles correctly, but there is a different error in testCompile.
3. Making both jackson-core and jackson-databind dependencies modular-jar type -> Compiles correctly, but there is a different error in testCompile.
The error in testCompile is:
>[ERROR] error: --patch-module specified more than once for module my.module.using.jackson

So, it seems to be a problem with the heuristics. Please note that in this case module-info.class is under META_INF/versions, not META-INF/services.

By the way, now that I tried it, these new dependency types make dependency management much more complicated, because, potentially, you could need to manage each dependency three times: one for type jar, one for type classpath-jar and one for type modular-jar.

**Comment by desruisseaux** [comment]
`META-INF/services/` was my typo. Indeed we mean `META-INF/version/`.

To my knowledge, the types declarations are not transitive, so it is normal that setting the type of `jackson-databind` has no effect on the type of `jackson-core dependency`. Maybe the type should be transitive, that would be an open question.

Regarding the error about `--patch-module`, I would like to know if this error is still present on 4.0.0-beta-3. Testing would require downloading Maven 4.0.0-rc-4, running `mvn install` on the master branch of the compiler plugin and setting the plugin version to `4.0.0-beta-3-SNAPSHOT` in your project. Additionally, if you have a chance to test with the #959 pull request as well, that would be great.

There is probably a regression in the heuristic regarding the scanning of `META-INF/version/`, but fixing that heuristic would only make the plugin behaves as if `<type>modular-jar</type>` has been specified. The `--patch-module` issue is a different problem, not caused by the heuristic.

**Comment by jafarre-bi** [comment]
> I think that as single parent POM would still work as today, after we fix the regression. As a bonus, there will be an extra level of control when desired:

Thank you, I misunderstood your previous message. This is fine for me, then.
About the problem with the --patch-module, it may be due to the code under test being modular, but the tests not declaring a module themselves. They are unit tests in the same package as the code under test, and that module is being automatically patch with the test classes added to it. May it be that when specifying the dependencies as module-jar there is another module patching over the previous one and that's the reason why --patch-module is duplicate?

**Comment by jafarre-bi** [comment]
With beta-3, the duplicate --patch-module doesn't happen, but I get a different error. It's a bit unsettling because in this case, it doesn't even mention the dependency, only the module I'm compiling and unit testing.
I attach the log: 

[log.txt](https://github.com/user-attachments/files/22435779/log.txt)

**Comment by desruisseaux** [comment]
> It still can't find the dependency module, unless I specify module-jar.

It is normal. As said in above comment, what has been improved in 4.0.0-beta-3 is the handling of `--patch-module` option. The search for module-info in `META-INF/services` is a separated issue.

For the error that you get, would it be possible to send a test case?

**Comment by jafarre-bi** [comment]
While trying to create a minimal reproducer (not yet done) I realised about this message while compiling main sources:
```
[WARNING] Filename-based automodules detected on the module path:
  - jackson-core-3.0.0-rc9.jar
Please don't publish this project to a public artifact repository.
```
Looks like it isn't detecting the module-info.class, it's just considering Jackson as an automodule.

**Comment by desruisseaux** [comment]
The test case worked file on my machine with Java 24 and without toolchains (because I don't have it configured on my machine). Would it be possible to test the following?

* Without toolchains
* With Java 24 or older

As a side note, the issue about finding `module-info.class` in `META-INF/versions/` sub-directories is addressed by a pull request on Maven core: https://github.com/apache/maven/pull/11153

**Comment by jafarre-bi** [comment]
Yes, I apologise for not explaining it properly. That's a minimal reproducer, so the toolchains plugin is required to reproduce the error.
The conclusion IMO is that the error happens when you compile unit tests in a modular project using the toolchains plugin.
I just tested with Java 21, and the error still occurs.

**Comment by jafarre-bi** [comment]
> As a side note, the issue about finding `module-info.class` in `META-INF/versions/` sub-directories is addressed by a pull request on Maven core: [apache/maven#11153](https://github.com/apache/maven/pull/11153)

I'm afraid I don't have time to build a custom Maven distribution. I'll have to wait for the rc-5. Is there any expected date for it?

**Comment by jafarre-bi** [comment]
Confirmed. With compiler version beta-3, and compiling the master branch of Maven, the problem is solved.
Thank you!
